#!/usr/bin/env bash
USERNAME=volgactf
IMAGE=volgactf-final-devenv-master

version=`cat VERSION`
echo "version: $version"

npm i
npm run build
docker tag $USERNAME/$IMAGE:latest $USERNAME/$IMAGE:$version
docker push $USERNAME/$IMAGE:latest
docker push $USERNAME/$IMAGE:$version
